#CI项目
name: ipq60xx-nowifi-libWrt

#CI计划
on:
  # 手动执行
  workflow_dispatch:
  # 默认为utc时间，北京时间需要减去8
  schedule:
    - cron: 0 13 1/7 * *

#CI权限
permissions: write-all

#CI任务
jobs:
  build:
    name: ipq60xx-nowifi-libWrt



    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/core.yml
    with:
      #编译平台
      TARGET: ipq60xx-nowifi-libWrt
      #源码
      REPO_SOURCE: LibWrt
      #源码地址
      REPO_URL: https://github.com/LiBwrt/openwrt-6.x
      #源码分支
      REPO_BRANCH: k6.12-nss
      #软件源
      FEEDS_CONF: feeds.conf.default
      #配置文件
      CONFIG_FILE: ./config/libWrt/nowifi.config

